import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          {/*   header */}
          <Header></Header>
          <main className="min-h-screen">{children}</main>
          {/* fotter */}
          <fotter className="bg-muted/50 py-12">
            <div className="container px-4 text-center text-gray-200 mx-auto">
              <p>Made with 💟 by NITESH-DK</p>
            </div>
          </fotter>
        </ThemeProvider>
      </body>
    </html>
  );
}
